openapi: 3.0.1
info:
  title: FRIDA PensionSerivce
  description: 
    $ref: './docs/FRIDA_PensionInformation_OA3/description_de.md'
  termsOfService: 'https://github.com/FRIDA-official'
  contact:
    $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/info/contact'
  license:
    $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/info/license'
  version: 0.0.1
externalDocs:
  $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/externalDocs'
  
servers:
  - url: 'https://test-api-impl-backend-jaxrs.herokuapp.com/v2'
paths:
  $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/paths'
components:
  $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/components'